# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logFC <- function(A, B) {
    .Call(`_RcppTestArea_logFC`, A, B)
}

StatTest <- function(X, test, backgound, logFCcut = 1.0, display_progress = TRUE) {
    .Call(`_RcppTestArea_StatTest`, X, test, backgound, logFCcut, display_progress)
}

ZScore <- function(data, display_progress = TRUE) {
    .Call(`_RcppTestArea_ZScore`, data, display_progress)
}

